stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${CF_REGION_ID}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf create-service "cloudantNoSQLDB" "Lite" "gyui-Cloudant-t8l3"
      cf create-service "compose-for-redis" "Standard" "gyui-Redis-x9h2"
      cf create-service "Object-Storage" "Free" "gyui-ObjectStorage-h5r6"
      cf create-service "AdvancedMobileAccess" "Graduated tier" "gyui-AppID-l9a0"
      cf create-service Auto-scaling free "gyui-AutoScaling-o7u5"
      cf push "${CF_APP}"
      # cf logs "${CF_APP}" --recent
